name: Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          pip install -U pip poetry
          poetry self add "poetry-dynamic-versioning[plugin]"

      - name: Cache
        uses: actions/cache@v4
        with:
          path: .venv
          key: release-${{ hashFiles('pyproject.toml') }}

      - name: Install dependencies
        run: poetry install --without dev

      - name: Build
        run: poetry build

      - name: Publish
        run: poetry publish -u $USER -p $PASSWORD
        env:
          USER: __token__
          PASSWORD: ${{ secrets.PYPI_TOKEN }}
